force-app/main/default/objects/NominationCategory__c/NominationCategory__c.object-meta.xml
<CustomObject>
    <description>Object is created to store the Nomination Name.</description>
    <label>Nomination Category</label>
    <nameField>
        <label>Nomination Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomination Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NomineeInNominationCategory__c/NomineeInNominationCategory__c.object-meta.xml
<CustomObject>
    <description>Object is created to store relationship between  Nominee and Nomination Category. However each Nominee take part in many Nomination Category, so User should vote for Nominee In Nomination Category.</description>
    <label>Nominee In Nomination Category</label>
    <nameField>
        <label>Nominee In Nomination Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominees In Nomination Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NomineeInNominationCategory__c/fields/NominationCategoryId__c.field-meta.xml
<CustomField>
    <fullName>NominationCategoryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nomination name</description>
    <inlineHelpText>Nomination name</inlineHelpText>
    <label>Nomination Category Id</label>
    <referenceTo>NominationCategory__c</referenceTo>
    <relationshipLabel>Nominees In Nomination Category</relationshipLabel>
    <relationshipName>NomineesInNominationCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NomineeInNominationCategory__c/fields/NomineeId__c.field-meta.xml
<CustomField>
    <fullName>NomineeId__c</fullName>
    <description>Person who has successfully passed approval process.</description>
    <inlineHelpText>Person who has successfully passed approval process.</inlineHelpText>
    <label>Nominee Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nominee In Nomination Categories</relationshipLabel>
    <relationshipName>NomineeInNominationCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NomineeInNominationCategoryTrH.cls
public class NomineeInNominationCategoryTrH extends TriggerHandler{
	
    public override void beforeInsert(){
        List<NomineeInNominationCategory__c> newNincs = (List<NomineeInNominationCategory__c>)Trigger.new;
        String nameNinc = '';
       
        Map<Id, Contact> conts = new Map<Id, Contact>([SELECT Id, FirstName, LastName, Email 
                                                       FROM Contact]);
        Map<Id, NominationCategory__c> nomCats = new Map<Id, NominationCategory__c>([SELECT Id, Name 
                                                                                     FROM NominationCategory__c]);
        for(NomineeInNominationCategory__c tmpNinc: newNincs){
             nameNinc = nomCats.get(tmpNinc.NominationCategoryId__c).Name +
               			  ' - ' + conts.get(tmpNinc.NomineeId__c).FirstName + 
                			' ' + conts.get(tmpNinc.NomineeId__c).LastName +
               			   ' ('  + conts.get(tmpNinc.NomineeId__c).Email + ')';
            tmpNinc.Name = nameNinc;
        }
    }
}