force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Object is created to store the nominations contained three of the best employees of the consequent position</description>
    <label>Nomination</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>Nomination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/BrokenRuleName__c.field-meta.xml
<CustomField>
    <fullName>BrokenRuleName__c</fullName>
    <description>Field is created to show a nomination rule type broken by the Nominator.</description>
    <externalId>true</externalId>
    <inlineHelpText>Field is created to show a nomination rule type broken by the Nominator.</inlineHelpText>
    <label>Broken Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/NominationCategoryId__c.field-meta.xml
<CustomField>
    <fullName>NominationCategoryId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Nomination Category for the Nominee.</description>
    <inlineHelpText>Select the existed Nomination Category for the Nominee or create a new one.</inlineHelpText>
    <label>Nomination Category Id</label>
    <referenceTo>NominationCategory__c</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/NominatorId__c.field-meta.xml
<CustomField>
    <fullName>NominatorId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is created to represent the person who nominates the Nominee.</description>
    <inlineHelpText>This field is created to represent the person who nominates the Nominee.</inlineHelpText>
    <label>Nominator Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>About My Nominee</relationshipLabel>
    <relationshipName>AboutMyNominee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/NomineeId__c.field-meta.xml
<CustomField>
    <fullName>NomineeId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Field is created to point a person who is nominated by the Nominator Id.</description>
    <inlineHelpText>Choice a person for The Nomination.</inlineHelpText>
    <label>Nominee Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>About Me</relationshipLabel>
    <relationshipName>AboutMe</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field is created to represent a status of approval process.</description>
    <inlineHelpText>In Approval
Approved
Rejected</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
                <default>true</default>
                <label>In Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NomineeInNominationCategory__c/NomineeInNominationCategory__c.object-meta.xml
<CustomObject>
    <description>Object is created to store relationship between  Nominee and Nomination Category. However each Nominee take part in many Nomination Category, so User should vote for Nominee In Nomination Category.</description>
    <label>Nominee In Nomination Category</label>
    <nameField>
        <label>Nominee In Nomination Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominees In Nomination Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NomineeInNominationCategory__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is created to show has the Nominee successfully passed approval process.</description>
    <inlineHelpText>Field is created to show has the Nominee successfully passed approval process.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NomineeInNominationCategory__c/fields/NominationCategoryId__c.field-meta.xml
<CustomField>
    <fullName>NominationCategoryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nomination name</description>
    <inlineHelpText>Nomination name</inlineHelpText>
    <label>Nomination Category Id</label>
    <referenceTo>NominationCategory__c</referenceTo>
    <relationshipLabel>Nominees In Nomination Category</relationshipLabel>
    <relationshipName>NomineesInNominationCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NomineeInNominationCategory__c/fields/NomineeId__c.field-meta.xml
<CustomField>
    <fullName>NomineeId__c</fullName>
    <description>Person who has successfully passed approval process.</description>
    <inlineHelpText>Person who has successfully passed approval process.</inlineHelpText>
    <label>Nominee Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nominee In Nomination Categories</relationshipLabel>
    <relationshipName>NomineeInNominationCategories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NominationTrH.cls
public class NominationTrH extends TriggerHandler{
    
    public NominationTrH(){
    }
    public override void beforeInsert(){
        List<Nomination__c> newNominations = (List<Nomination__c>)Trigger.new;
        Set<Id> newNomorIds = new Set<Id>();
        
        for(Nomination__c tmpNom : newNominations){
           newNomorIds.add(tmpNom.NominatorId__c);
        }
        List<String> breakFirstRuleKeys = new List<String>();
        String keyFirstRule = '';
        
        Map<String, List<Nomination__c>> breakSecondRuleKeys = new Map<String, List<Nomination__c>>();
        String keySecondRule = '';
        
        for(Nomination__c tmpNom : [SELECT Id, NominatorId__c, NomineeId__c, NominationCategoryId__c
                                    FROM Nomination__c]){
            keyFirstRule = ''+ tmpNom.NomineeId__c + ',' + 
                               tmpNom.NominatorId__c + ',' + 
                               tmpNom.NominationCategoryId__c;
            keySecondRule = '' + tmpNom.NominatorId__c + ',' + 
                                 tmpNom.NominationCategoryId__c;
            breakFirstRuleKeys.add(keyFirstRule);

            if(!breakSecondRuleKeys.containsKey(keySecondRule)){
                breakSecondRuleKeys.put(keySecondRule, new List<Nomination__c>());
            }  
            breakSecondRuleKeys.get(keySecondRule).add(tmpNom);
        }
        
        Boolean isBreakFirstRule = false;
        Boolean isBreakSecondRule = false;
        for(Nomination__c tmpNom : (List<Nomination__c>)Trigger.new){
            keyFirstRule = ''+ tmpNom.NomineeId__c + ',' + 
                               tmpNom.NominatorId__c + ',' + 
                               tmpNom.NominationCategoryId__c;
            keySecondRule = '' + tmpNom.NominatorId__c + ',' +
                                 tmpNom.NominationCategoryId__c;
            if(breakFirstRuleKeys.contains(keyFirstRule)){
                isBreakFirstRule = true;
                break;
            }else{
                breakFirstRuleKeys.add(keyFirstRule);
            }
            if(breakSecondRuleKeys.containsKey(keySecondRule)){
                breakSecondRuleKeys.get(keySecondRule).add(tmpNom);
                
                if(breakSecondRuleKeys.get(keySecondRule).size() > 3){
                	isBreakSecondRule = true;
                	break;
                }
            } else {
                breakSecondRuleKeys.put(keySecondRule, new List<Nomination__c>());
            }
        }
        String brokenRuleMessage = 'Any';
        if(isBreakFirstRule){
            brokenRuleMessage = 'TwiceNomineePerNomination';
        } else if(isBreakSecondRule){
            brokenRuleMessage = 'ThreeNomineesPerNomination';
        }
        for(Nomination__c tmpNomination : newNominations){
           		 tmpNomination.BrokenRuleName__c = brokenRuleMessage;
        	}
        
    }    
   
    public override void afterInsert(){
        // Create and input new NomineeInNominationCategory obj if it is absent. 
        Set<String> existNincNames = new Set<String>();
        for(NomineeInNominationCategory__c tmpNinc : [SELECT Id, NominationCategoryId__c, NomineeId__c 
                                                      FROM NomineeInNominationCategory__c]){
            existNincNames.add(''+ tmpNinc.NominationCategoryId__c + tmpNinc.NomineeId__c);
        }
        List <NomineeInNominationCategory__c> absentNincs = new List <NomineeInNominationCategory__c>();
        String keyNameAbsentNinc = '';
        for(Nomination__c tmpNom : [SELECT Id, NomineeId__c, NominationCategoryId__c
                                    FROM Nomination__c
                                    WHERE Id IN :Trigger.new]){
            keyNameAbsentNinc = ''+ tmpNom.NominationCategoryId__c + tmpNom.NomineeId__c;
            if(!existNincNames.contains(keyNameAbsentNinc)){
                absentNincs.add(new NomineeInNominationCategory__c(
                                            NominationCategoryId__c = tmpNom.NominationCategoryId__c,
                				 			NomineeId__c = tmpNom.NomineeId__c,
                				 			Active__c = false));
                existNincNames.add(keyNameAbsentNinc);  
                
            }
        }
       	if(!absentNincs.isEmpty()){
            	insert absentNincs;
        }
    }

    public override void afterUpdate(){
        //Change Active field (NomineeInNominationCategory obj) to true if nomination has been approved
        Map<Id, Nomination__c> oldInAprovalNoms = (Map<Id, Nomination__c>)Trigger.oldMap;
        Map<String, Nomination__c> nomsWithChange = new Map <String, Nomination__c>();
        String key ='';
        String optionStatus = '';
        for(Nomination__c tmpNom : [SELECT Id, Status__c, NominationCategoryId__c, NomineeId__c 
                                    FROM Nomination__c 
                                    WHERE Id IN :Trigger.New 
                                    AND Status__c = 'Approved']){
            optionStatus = oldInAprovalNoms.get(tmpNom.Id).Status__c;                           
            if (optionStatus == 'In Approval'){
                key = ''+ tmpNom.NominationCategoryId__c +
                          tmpNom.NomineeId__c;
                nomsWithChange.put(key, tmpNom);
            } 
        }
        List<NomineeInNominationCategory__c> nincToUpdate = new List <NomineeInNominationCategory__c>();
        for(NomineeInNominationCategory__c tmpNinc : [SELECT Id, NominationCategoryId__c, NomineeId__c
                                                      FROM NomineeInNominationCategory__c]){
            key = ''+ tmpNinc.NominationCategoryId__c + 
                      tmpNinc.NomineeId__c;   
            if(nomsWithChange.containsKey(key)){
                 tmpNinc.Active__c = true;
                 nincToUpdate.add(tmpNinc);
            }                                              
        }
        if(!nincToUpdate.isEmpty()){
           update nincToUpdate; 
        }
        
 
    }
    
 
}