force-app/main/default/objects/Nomination__c/Nomination__c.object-meta.xml
<CustomObject>
    <description>Object is created to store the nominations contained three of the best employees of the consequent position</description>
    <label>Nomination</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>Nomination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomination__c/fields/NominationCategoryId__c.field-meta.xml
<CustomField>
    <fullName>NominationCategoryId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Nomination Category for the Nominee.</description>
    <inlineHelpText>Select the existed Nomination Category for the Nominee or create a new one.</inlineHelpText>
    <label>Nomination Category Id</label>
    <referenceTo>NominationCategory__c</referenceTo>
    <relationshipLabel>Nominations</relationshipLabel>
    <relationshipName>Nominations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/NominatorId__c.field-meta.xml
<CustomField>
    <fullName>NominatorId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is created to represent the person who nominates the Nominee.</description>
    <inlineHelpText>This field is created to represent the person who nominates the Nominee.</inlineHelpText>
    <label>Nominator Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>About My Nominee</relationshipLabel>
    <relationshipName>AboutMyNominee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/NomineeId__c.field-meta.xml
<CustomField>
    <fullName>NomineeId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Field is created to point a person who is nominated by the Nominator Id.</description>
    <inlineHelpText>Choice a person for The Nomination.</inlineHelpText>
    <label>Nominee Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>About Me</relationshipLabel>
    <relationshipName>AboutMe</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nomination__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <description>About your Nominee.</description>
    <inlineHelpText>Why do you nominate this person?</inlineHelpText>
    <label>Review</label>
    <length>3000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NominationCategory__c/NominationCategory__c.object-meta.xml
<CustomObject>
    <description>Object is created to store the Nomination Name.</description>
    <label>Nomination Category</label>
    <nameField>
        <label>Nomination Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomination Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestNominationInsertion.cls
@isTest
public class TestNominationInsertion {
    
    @testSetup static void setup() {
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        List<Contact> conts = TestDataFactory.createTenDiffContact();
        List<NominationCategory__c> nomCats = TestDataFactory.createTenDiffNominationCategory();
        insert conts;
        insert nomCats;
        List<Nomination__c> noms = new List<Nomination__c>();
        for(Integer i = 0; i < 3; i++){
            noms.add(new Nomination__c(NomineeId__c = conts.get(i).Id, 
                                       NominatorId__c = conts.get(4).Id, 
                                       NominationCategoryId__c = nomCats.get(1).Id, 
                                       Review__c = TestDataFactory.createTenWellReview().get(i)));
        }
        insert noms;
        
        
    }
  
   // before insert
     @isTest static void testOneFollowRules(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //----------------
        //[ 1 - 5 - 2 ]
        List<Contact> conts = [SELECT Id 
                               FROM Contact];
        List<NominationCategory__c> nomCats = [SELECT Id 
                                               FROM NominationCategory__c ];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(2).Id, 
                                         NominatorId__c = conts.get(5).Id, 
                                         NominationCategoryId__c = nomCats.get(1).Id, 
                                         Review__c = TestDataFactory.createTenWellReview().get(9)));
        Test.startTest();
        Database.SaveResult result = Database.insert(addNewNoms[0]);
        Test.stopTest();
        System.assert(result.isSuccess()); 
     }
    
    @isTest static void testBulkFollowRules(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //--------------
        //[ 1 - 5 - 0 ]
        //[ 1 - 5 - 1 ]
        //[ 1 - 5 - 2 ]
        List<Contact> conts = [SELECT Id FROM Contact];
        List<NominationCategory__c> nomCats = [SELECT Id FROM NominationCategory__c ];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        for(Integer i = 0; i < 3; i++){
            addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(i).Id, 
                                            NominatorId__c = conts.get(5).Id, 
                                            NominationCategoryId__c = nomCats.get(1).Id, 
                                            Review__c = TestDataFactory.createTenWellReview().get(i)));
        }
        Test.startTest();
        Database.SaveResult[] results = Database.insert(addNewNoms);
        Test.stopTest();
        
        for(Database.SaveResult item : results) {
            System.assert(item.isSuccess());
        }
    }
  
    @isTest static void testOneBreakRuleThreeNomineesPerNomination(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //--------------
        //[ 1 - 4 - 3 ]
        
        List<Contact> conts = [SELECT Id, Email 
                               FROM Contact]; 
        List<NominationCategory__c> nomCats = [SELECT Id 
                                               FROM NominationCategory__c];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(3).Id, 
                                         NominatorId__c = conts.get(4).Id, 
                                   		 NominationCategoryId__c = nomCats.get(1).Id, 
                                  		 Review__c = TestDataFactory.createTenWellReview().get(7)));
        Test.startTest();
        Database.SaveResult result = Database.insert(addNewNoms[0], false);
        Test.stopTest();
        
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('You choose more than three Nominees in the same Nomination Category.',
                                 result.getErrors()[0].getMessage());  
    }
    
    @isTest static void testBulkBreakRuleThreeNomineesPerNomination(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //--------------
        //[ 1 - 4 - 5 ]
        //[ 1 - 4 - 6 ]
        //[ 1 - 4 - 7 ]
        List<Contact> conts = [SELECT Id, Email 
                               FROM Contact]; 
        List<NominationCategory__c> nomCats = [SELECT Id 
                                               FROM NominationCategory__c];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        for(Integer i = 5; i <= 7; i++){
            addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(i).Id, 
                                            NominatorId__c = conts.get(4).Id, 
                                            NominationCategoryId__c = nomCats.get(1).Id, 
                                            Review__c = TestDataFactory.createTenWellReview().get(i)));
        }
        Test.startTest();
        Database.SaveResult[] results = Database.insert(addNewNoms, false);
        Test.stopTest();
        
        for(Database.SaveResult item : results) {
            System.assert(!item.isSuccess());
            System.assert(item.getErrors().size() > 0);
            System.assertEquals('You choose more than three Nominees in the same Nomination Category.',
                                 item.getErrors()[0].getMessage());
        }
    }
    
     @isTest static void testOneBreakRuleTwiceNomineePerNomination(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //--------------
        //[ 1 - 4 - 2 ]
        
        List<Contact> conts = [SELECT Id, Email 
                               FROM Contact]; 
        List<NominationCategory__c> nomCats = [SELECT Id 
                                               FROM NominationCategory__c];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(2).Id, 
                                         NominatorId__c = conts.get(4).Id, 
                                   		 NominationCategoryId__c = nomCats.get(1).Id, 
                                  		 Review__c = TestDataFactory.createTenWellReview().get(7)));
        Test.startTest();
        Database.SaveResult result = Database.insert(addNewNoms[0], false);
        Test.stopTest();
        
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('You cannot nominate the Nominee in the Nomination Category twice.',
                                 result.getErrors()[0].getMessage());  
    }
    
    @isTest static void testBulkBreakRuleTwiceNomineePerNomination(){
        //[nomCat - nominator - nominee ]
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        //--------------
        //[ 1 - 4 - 0 ]
        //[ 1 - 4 - 1 ]
        //[ 1 - 4 - 2 ]
        List<Contact> conts = [SELECT Id, Email 
                               FROM Contact]; 
        List<NominationCategory__c> nomCats = [SELECT Id 
                                               FROM NominationCategory__c];
        List<Nomination__c> addNewNoms = new List<Nomination__c>();
        for(Integer i = 0; i <= 2; i++){
            addNewNoms.add(new Nomination__c(NomineeId__c = conts.get(i).Id, 
                                             NominatorId__c = conts.get(4).Id, 
                                             NominationCategoryId__c = nomCats.get(1).Id, 
                                             Review__c = TestDataFactory.createTenWellReview().get(i)));
        }
        Test.startTest();
        Database.SaveResult[] results = Database.insert(addNewNoms, false);
        Test.stopTest();
        
        for(Database.SaveResult item : results) {
            System.assert(!item.isSuccess());
            System.assert(item.getErrors().size() > 0);
            System.assertEquals('You cannot nominate the Nominee in the Nomination Category twice.',
                                 item.getErrors()[0].getMessage());
        }
    }
    /*
    //after insert
    @isTest static void testOneAddNewNINC(){}
    
    @isTest static void testBulkAddNewNINC(){}
    
    @isTest static void testOneAddExistNINC(){}
    
    @isTest static void testBulkAddExistNINC(){}
    
    //after update
    @isTest static void testOneActivateApprovedNINC(){}
    @isTest static void testBulkActivateApprovedNINC(){}
    @isTest static void testOneNotChangeRejectedNINC(){}
    @isTest static void testBulkNotChangeRejectedNINC(){}
    */
   

}